### ISSUE TITLE
Errro on hover_doc

### ISSUE THREAD

**Issue by bluespada** [glepnir/lspsaga.nvim#347] opened 2022-07-07 12:17 UTC
### Description

Error on opening winbar

**Expected Behavior**

Opening `lspsaga hover_doc`

**Actual Behavior**

error : 
```
Error executing vim.schedule lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:184: Invalid option name 'winbar'
stack traceback:
        [C]: in function 'nvim_win_set_option'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:184: in function 'create_win_with_border'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:338: in function 'fancy_floating_markdown'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:32: in function 'fn'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:13: in function 'focusable_float'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:21: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1025: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

**Neovim Built in Behavior**

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: `NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3`
- Operating system: Fedora 36
- lspsaga commit: 

</details>

**Comment by nullchilly** [comment] 2022-07-07 12:40
Duplicate of https://github.com/glepnir/lspsaga.nvim/issues/321 ?

**Closed** 2022-07-07 12:42 UTC
Labels: bug
