### ISSUE TITLE
Nothing happens after install

### ISSUE THREAD

**Issue by lucazz** [glepnir/lspsaga.nvim#352] opened 2022-07-08 15:01 UTC
### Description
Hello there everyone, 

I'm trying this plugin out, but nothing happens after plugin install, none of the configs added seem to render any effect. 
If I change the configs to something that the plugin is not expecting, I get error messages, so the code is indeed being evaluated.

**Expected Behavior**
Plugin should work as show in the docs

**Actual Behavior**
Nothing happens. No hovers, No code actions, anything..

### Details

<details><summary>Reproduce</summary>

I've installed lspsaga and configured it using the following snippet: 
```
local saga = require 'lspsaga'
local action = require("lspsaga.action")
local action = require("lspsaga.codeaction")

saga.init_lsp_saga{
  border_style = "rounded",
  diagnostic_header = { " ", " ", " ", "ﴞ " },
  code_action_icon = "",
  code_action_num_shortcut = true,
  code_action_lightbulb = {
    enable = true,
    sign = true,
    sign_priority = 20,
    virtual_text = true,
  },
  finder_separator = "  ",
  max_preview_lines = 10,
  finder_action_keys = {
    open = "o",
    vsplit = "s",
    split = "i",
    tabe = "t",
    quit = "q",
    scroll_down = "<C-f>",
    scroll_up = "<C-b>", -- quit can be a table
  },
  code_action_keys = {
    quit = "q",
    exec = "<CR>",
  },
  rename_action_quit = "<C-c>",
  definition_preview_icon = " ",
  symbol_in_winbar = {
    in_custom = false,
    enable = false,
    separator = ' ',
    show_file = true,
    click_support = false,
  },
}

vim.keymap.set("n", "K", "<cmd>Lspsaga hover_doc<CR>", { silent = true })
vim.keymap.set("n", "gd", "<cmd>Lspsaga preview_definition<CR>", { silent = true })
vim.keymap.set("n", "<leader>ca", "<cmd>Lspsaga code_action<CR>", { silent = true,noremap = true })
vim.keymap.set("v", "<leader>ca", "<cmd><C-U>Lspsaga range_code_action<CR>", { silent = true,noremap = true })
vim.keymap.set("n", "gh", "<cmd>Lspsaga lsp_finder<CR>", { silent = true,noremap = true})
vim.cmd [[autocmd! CursorHold,CursorHoldI * lua require'lspsaga.diagnostic'.show_line_diagnostics()]]

vim.keymap.set("n", "<C-f>", function()
  action.smart_scroll_with_saga(1)
end, { silent = true })

vim.keymap.set("n", "<C-b>", function()
  action.smart_scroll_with_saga(-1)
end, { silent = true })

click_support = function(node, clicks, button, modifiers)
    -- To see all avaiable details: vim.pretty_print(node)
    local st = node.range.start
    local en = node.range['end']
    if button == "l" then
        if clicks == 2 then
            -- double left click to do nothing
        else -- jump to node's starting line+char
            vim.fn.cursor(st.line + 1, st.character + 1)
        end
    elseif button == "r" then
        if modifiers == "s" then
            print "lspsaga" -- shift right click to print "lspsaga"
        end -- jump to node's ending line+char
        vim.fn.cursor(en.line + 1, en.character + 1)
    elseif button == "m" then
        -- middle click to visual select node
        vim.fn.cursor(st.line + 1, st.character + 1)
        vim.cmd "normal v"
        vim.fn.cursor(en.line + 1, en.character + 1)
    end
end
```
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```
- Operating system: macOS Monterey 12.4 
- lspsaga commit: 9922e17c8e535328462fa246cc8fde32d9f72371

</details>

**Comment by nullchilly** [comment] 2022-07-08 17:52
You need to install lsp servers using https://github.com/neovim/nvim-lspconfig first

@glepnir Maybe the `click_support` readme is a bit misleading?

**Comment by lucazz** [comment] 2022-07-08 19:07
I have a couple servers installed already:
<img width="1443" alt="Screen Shot 2022-07-08 at 16 07 01" src="https://user-images.githubusercontent.com/6126301/178055273-d33545bf-420e-4cfd-a15d-50e7eef200ff.png">

Let me try and remove `winbar`

**Comment by lucazz** [comment] 2022-07-08 19:09
I thinkn there's some other plugin interaction preventing this from loading, hitting `K` over `*http` at line 10 renders it at the bottom section: 

<img width="1800" alt="Screen Shot 2022-07-08 at 16 08 43" src="https://user-images.githubusercontent.com/6126301/178055487-4fa4c659-b27b-45ad-ab42-2f4465f090de.png">

**Comment by lucazz** [comment] 2022-07-08 19:11
If anyone could please give me a hint on what might be taking place here or how to debug this, I'd appreciate it a lot! 
Here's my dotfiles, precisely the lsp setup: https://github.com/lucazz/dotfiles/tree/master/nvim/lua/config/lsp

**Comment by ipkiss42** [comment] 2022-07-08 20:36
FWIW, I had a similar issue and it turned out that I still had coc.nvim enabled. After using only nvim-lspconfig, Saga started working as expected.

**Comment by glepnir** [comment] 2022-07-09 02:16
@lucazz  `winbar` is a feature of neovim 0.8 . it can not work in 0.7. and use `verbose map K`. check your `k` map , I think has a conflict

**Comment by nullchilly** [comment] 2022-07-09 02:18
@glepnir I am running their config, there is no mapping for K, it's the default man.vim behavior

The problem is they thought nvim-lsp-installer auto setup servers configuration

**Comment by glepnir** [comment] 2022-07-09 02:19
I think the best way is use a min config to test. so maybe I can close this issue?

**Closed** 2022-07-09 02:26 UTC
Labels: bug

**Comment by nullchilly** [comment] 2022-07-09 02:50
@lucazz In `nvim/lua/config/lsp/lsp-installer` your code is broken
Here is a working version for lua
![image](https://user-images.githubusercontent.com/56817415/178088835-37ebe60b-088e-43a6-b957-9b7f6d60db0f.png)

If you are gonna source every plugin file in lua put them in `nvim/after/plugin` and they will load automatically after each plugin is loaded. For example, I put it in `nvim/after/plugin/lspsaga.lua` as shown in the screenshot.

**Comment by lucazz** [comment] 2022-07-09 15:18
Heya @nullchilly, thanks for the tip!
I did managed to fix my lsp-installer setup and everything works like a charm now.
<img width="451" alt="Screen Shot 2022-07-09 at 12 18 01" src="https://user-images.githubusercontent.com/6126301/178111821-8a0919c4-479f-4ac0-96e8-3d4e25480097.png">

**Comment by renkam** [comment] 2022-08-05 13:28
I have exactly same problem, lsp server is installed and running but no results from lspsaga
Moreover lspsaga is not giving any erorrs
How to debug this situation?

**Comment by glepnir** [comment] 2022-08-05 13:39
first check the file have lsp server information `LspInfo` then check the lspsaga loaded if you use packer you can try
`lua print(packer_plugins['lspsaga.nvim'].loaded)` true mean is load . if you don't use packer check the `rtp` path 
`set rtp?` it should be have lspsaga. press `Lspsaga Tab` if nothing happen that mean lspsaga not load

**Comment by renkam** [comment] 2022-08-05 13:53
Lspsaga looks like it was loaded, I have the command available.
but `LspInfo` is probably wrong:
```
Language client log: /home/rk/.cache/nvim/lsp.log
Detected filetype:   go                             
0 client(s) attached to this buffer:                
Configured servers list:                            
```
So this shows that nothing connected to lsp, but I can't tell if lsp is running correctly

**Comment by glepnir** [comment] 2022-08-05 14:01
> 0 client(s) attached to this buffer:

there should be 1 of gopls. so the gopls doesn't start for this buffer

**Comment by renkam** [comment] 2022-08-05 14:48
OK, thanks for quick response. I didn't configured `lspconfig` correctly, so `lspsaga` couldn't use it.
I wish `lspsaga` have some kind of `Lspsaga status` command so it could tell me if lsp is reachable
