### ISSUE TITLE
Issue: high memory leak

### ISSUE THREAD

**Issue by segfaulty1** [glepnir/lspsaga.nvim#585] opened 2022-11-11 10:35 UTC
### Description
a really big memory leak when invoking: `<Cmd>Lspsaga lsp_finder<CR>`
in a matter of seconds, my memory goes from 12% to 60%+

### Details
I know this is kind of unprofessional, I should probably dig a little bit into the code or reproduce the error in a minimal way.

<details><summary>Reproduce</summary>
!- basically I installed Lspsaga using packer<br>
2- I setup a keybinding for it<br>
3- I invoked the keybinding<br>

the memory consumption starts rising up. even after I quit the prompt of the `lsp_finder`.
the memory keeps going up, unless I quit the Neovim instance.

1. nvim min lspsaga config
```lua
local status, saga = pcall(require, 'lspsaga')
if (not status) then return end

saga.init_lsp_saga {
  server_filetype_map = {}
}
local keymap = vim.keymap.set
keymap('n', 'mf', '<Cmd>Lspsaga lsp_finder<CR>', opts)
```
</details>

<details><summary>Environment</summary>

- nvim --version output:  v0.7.2
- Operating system: debian-bookworm
- lspsaga commit: 201dbbd13d6bafe1144475bbcae9efde224e07ec

</details>

**Comment by glepnir** [comment] 2022-11-11 10:44
hmm I can't reproduce ? which project

**Comment by segfaulty1** [comment] 2022-11-11 22:52
I'm not sure what you mean!!

**Comment by glepnir** [comment] 2022-11-12 00:39
first i can't reproduce your issue. `lsp_finder` works fine with large project or normal project. Second I think you need use the min config that only have lspsaga to test.  and you need tell me which project you test on. if i still not reproduce I will close this issue.

**Comment by segfaulty1** [comment] 2022-11-12 04:33
hmm... yh I'm a little unprofessional, I think you just go ahead and close the issue. I'll give it a few updates and downgrades to see if things go better. it sounds like a rare case.

thank you for your effort.

**Comment by glepnir** [comment] 2022-11-12 05:14
if you can use a open source project reproduce. just tell me which repo. I will test this behavior.

**Comment by segfaulty1** [comment] 2022-11-13 08:02
ok leme put some effort...
ok I was able to reproduce the error with minimal setup:

The only installed plugins are: `neovim/nvim-lspconfig` and `glepnir/lspsga.nvim`

_**Sorry for the long lspconfig file.**_

## The config files for both lspconfig and lspsaga are:

### lspsaga.rc.lua:
```lua
local status, saga = pcall(require, 'lspsaga')
if (not status) then return end

saga.init_lsp_saga {
  server_filetype_map = {}
}

```
### lspconfig.rc.lua:
```lua
local status, lsp = pcall(require, 'lspconfig')
if (not status) then return end

local protocol = require('vim.lsp.protocol')

local on_attach = function(client)
  -- formatting
  if client.server_capabilities.documentFormattingProvider then
    vim.api.nvim_command [[augroup Format]]
    vim.api.nvim_command [[autocmd! * <buffer>]]
    vim.api.nvim_command [[autocmd BufWritPre <buffer> lua vim.lsp.buf.formatting_seq_sync()]]
    vim.api.nvim_command [[augroup END]]
  end
end

--Enable (broadcasting) snippet capability for completion
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

lsp.html.setup {
  capabilities = capabilities,
}

lsp.cssls.setup {
  capabilities = capabilities,
}

lsp.jsonls.setup {
  capabilities = capabilities,
}

lsp.bashls.setup{}

lsp.pyright.setup{}

lsp.tailwindcss.setup {}

lsp.eslint.setup {}

lsp.sumneko_lua.setup {
  settings = {
    Lua = {
      runtime = {
        -- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
        version = 'LuaJIT',
      },
      diagnostics = {
        -- Get the language server to recognize the `vim` global
        globals = {'vim'},
      },
      workspace = {
        -- Make the server aware of Neovim runtime files
        library = vim.api.nvim_get_runtime_file("", true),
        checkThirdParty = false
      },
      -- Do not send telemetry data containing a randomized but unique identifier
      telemetry = {
        enable = false,
      },
    },
  },
}
```

## And here is the test file:
```lua
local opts = { noremap = true, silent = false }
local keymap = vim.keymap.set

keymap('n', 'd', '"_d', opts)
```

## The expected buggy behavior is:
!. put your cursor on `opts` and run the `lsp_finder`.
2. it should work just fine
3. put your cursor on `keymap` and run the `lsp_finder`
4. it should start eating your memory now
5. hit the `Esc` key to stop the behavior, and it should not stop.
6. quit nvim and it will

I'm not sure if a big open source project vs. a small file should make a difference, since memory leakage is an unwanted behavior no matter what the use case is.

Let me know if I did something the wrong way, I'm new to nvim, lua and this lovely plugin.

**Comment by glepnir** [comment] 2022-11-13 08:32
can't reproduce.

![images](https://user-images.githubusercontent.com/41671631/201512908-ae4f05e6-6251-4dcd-a598-ad50e46202c5.gif)

**Closed** 2022-11-13 08:33 UTC
Labels: bug

**Comment by segfaulty1** [comment] 2022-11-15 07:08
hmmm, maybe it's the debian-testing repository.

**Comment by egorderg** [comment] 2022-11-21 22:22
It also happened to me, in my lsp config for sumneko i had this line to scan all files in the nvim runtime:

`library = vim.api.nvim_get_runtime_file("", true),`

When i started lsp_finder on something like vim.'keymap' or vim.'cmd' the ram usage jumped to 60% because i had 10 sumneko process with 600MB ram usage.

After i comment the line everything worked fine, i think it was just to much for the lsp service. Even in idle mode it used 600MB (single process)
