### ISSUE TITLE
Attempt to call field '_trim_and_pad' (a nil value)

### ISSUE THREAD

**Issue by creativenull** [glepnir/lspsaga.nvim#164] opened 2021-04-06 02:22 UTC
### Description

Issuing the commands `:Lspsaga hover_doc` or `:Lspsaga show_line_diagnostics` give me an error where `_trim_and_pad` function does not exist.

This is probably (not sure exactly) due to [this PR](https://github.com/neovim/neovim/pull/14207) in neovim where the `trim_and_pad` function was removed from their utility file.

**Expected Behavior**

Should show popup menu with the definition preview or diagnostic info.

**Actual Behavior**

![image](https://user-images.githubusercontent.com/3767728/113648834-46dcd500-965b-11eb-8fd3-7f8c9416a1b0.png)

**Neovim Built in Behavior**

### Details

<details><summary>Reproduce</summary>

1. Have nvim-lspconfig and lspsaga installed
2. Register the lsp via `require 'lspconfig'.tsserver.setup { on_attach = function(client) print('Attached to '.. client.name) end }`
3. Open a file supported by nvim-lsp (eg javascript/typescript file with typescript-language-server installed)
4. Run the command `:Lspsaga hover_doc`
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1225-gbbdd00203
- Operating system: Windows 10 using WSL2 (Ubuntu 20.04)
- lspsaga commit: 27c7a47

</details>

**Comment by lalitmee** [comment] 2021-04-07 19:49
Need a fix for this. :thinking: 
There is already a PR for this.

**Comment by marcelarie** [comment] 2021-04-08 08:16
I'm having the same error.
My version its NVIM v0.5.0-dev+1231-g48e805728
[![asciicast](https://asciinema.org/a/WeIhPyBavQIN7KDLSu3aCnhHJ.svg)](https://asciinema.org/a/WeIhPyBavQIN7KDLSu3aCnhHJ)

**Closed** 2021-04-09 07:08 UTC
Labels: bug

**Comment by cehoffman** [comment] 2021-04-10 06:38
I don't think the root cause was `_trim_and_pad`.

After updating to get this fix I get this error now.

> Error executing vim.schedule lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:175: attempt to call field '_trim' (a nil value)

**Comment by reejosamuel** [comment] 2021-04-26 15:24
![Screen Shot 2021-04-26 at 11 23 06 AM](https://user-images.githubusercontent.com/1253679/116108288-c7528c80-a681-11eb-85f0-327016f3e782.png)

I'm getting this error now.
