### ISSUE TITLE
`show_line_diagnostics` nil value

### ISSUE THREAD

**Issue by AlexvZyl** [glepnir/lspsaga.nvim#783] opened 2023-01-28 11:35 UTC
### Describe the bug

When running `:Lspsaga show_line_diagnostics` this happens:

![image](https://user-images.githubusercontent.com/81622310/215264265-4c0c92c0-2d73-4e96-b9c0-1ac7956b336f.png)

### Steps to reproduce

Using default values:

```lua
require 'lspsaga' .setup {}
```

Run `Lspsaga show_line_diagnostics` over any diagnostic.

### Expected behavior

Should not break.

### Neovim version (nvim -v)

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui

### lspsaga commit

f281c050aa85550ce9e60b33d082428d2b0a3ef1

### Terminal name/version

Alacritty 0.11.0 (8dbaa0bb).

**Comment by glepnir** [comment] 2023-01-28 13:05
can you update then give it a test

**Comment by glepnir** [comment] 2023-01-28 13:55
should be fixed. if not I will reopen.

**Closed by glepnir** 2023-01-28 13:55 UTC
Labels: bug

**Comment by AlexvZyl** [comment] 2023-01-28 19:34
Updated to latest and it is still not fixed.

**Comment by glepnir** [comment] 2023-01-28 23:03
how you triggered?

**Comment by glepnir** [comment] 2023-01-29 00:21
I can't reproduce. that issue like you trigger cr map in window.

**Comment by rorj** [comment] 2023-01-29 10:38
I'm having the same issue. Calling `Lspsaga show_line_diagnostics` on line with an error:

```
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui 

Error executing Lua callback: ...ack/packer/start/lspsaga.nvim/lua/lspsaga/diagnostic.lua:505: attempt to concatenate field 'text' (a nil value)                                                                                            
stack traceback:                                                                                                                                                                                                                            
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/diagnostic.lua:505: in function 'show'                                                                                                                                                 
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/diagnostic.lua:627: in function 'show_diagnostics'                                                                                                                                     
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:23: in function <...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:22>                                                                                        
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:60: in function 'load_command'                                                                                                                                          
        ...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:7>
```

**Comment by KPatr1ck** [comment] 2023-02-23 10:28
I have the same issue after this commit: https://github.com/glepnir/lspsaga.nvim/commit/51e3f2b180151937361e0cc9374de2a7359c16ae

I solved it by the setting:
```lua
-- Diagnostic setting
vim.diagnostic.config({
    virtual_text = true,
    signs = true,
    update_in_insert = false,
})
```
