### ISSUE TITLE
rust-analyzer - codeaction.lua:112: attempt to index local 'action' (a number value)

### ISSUE THREAD

**Issue by thorlucas** [glepnir/lspsaga.nvim#250] opened 2021-09-28 02:36 UTC
### Description
When running `lua require('lspsaga.codeaction').code_action()` in a rust file, we get the following error:

```
Error executing vim.schedule lua callback:
...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:112:
attempt to index local 'action' (a number value)
```

### Details

<details><summary>Reproduce</summary>

1. Install `rust-tools` and set up

2. Open a rust document

3. Run `lua require('lspsaga.codeaction').code_action()`
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.6.0-dev+356-gbec7f47ce
- Operating system: macOS 11.5.2
- lspsaga commit: cb0e35d2e594ff7a9c408d2e382945d56336c040

</details>

**Comment by MonstrousOgre** [comment] 2021-09-29 13:14
I'm facing the same in both Rust and Node js files. It was working fine earlier and I didn't change anything, so a recent change may have broken it.

I'm using Neovim 0.5.1

**Comment by jan-xyz** [comment] 2021-09-29 15:46
I think this is caused by the API changes in NVIM 0.5.1?

**Comment by al3xfischer** [comment] 2021-09-29 16:24
@jan-xyz I think you are right.

I tested it with 0.5.0 and 0.5.1.
- 0.5.0
  Works fine
- 0.5.1 
  I get the mentioned error 

I could also reproduce the error with other languages as well.
- tsserver
- omnisharp
- pyrigth

**Comment by al3xfischer** [comment] 2021-09-30 06:34
Duplicate of #241

**Closed** 2022-06-22 13:37 UTC
Labels: bug
