### ISSUE TITLE
Inconsistent hoverdoc width

### ISSUE THREAD

**Issue by gshpychka** [glepnir/lspsaga.nvim#124] opened 2021-02-25 15:27 UTC
### Description
Hoverdoc width is not consistent, and I have not been able to figure out the rule.

![image](https://user-images.githubusercontent.com/23005347/109175300-57fa1280-778e-11eb-8eae-a4f9de99684c.png)
![image](https://user-images.githubusercontent.com/23005347/109175315-5a5c6c80-778e-11eb-8933-f1e28f3f3ec0.png)

Also, when the width spans the full window, it doesn't render properly, as you can see on the left side in the second screenshot.

**Expected Behavior**
Full width hover_doc in both cases, with proper borders.

**Actual Behavior**
Most of the time the float window is too narrow, sometimes it is wide but with a rendering issue.

**Neovim Built in Behavior**
Neovim's float window are not limited in width (only by the vim window itself)

### Details

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1109-g6b7cc45c4
- Operating system: archlinux
- lspsaga commit: 971df939422be657856f151f0b184d767fe89927

</details>

**Comment by glepnir** [comment] 2021-02-26 02:20
How about now. If still has problem .reopen then.

**Comment by gshpychka** [comment] 2021-02-26 06:00
I cannot reopen it if I'm not the one who closed it. It's not solved. Here's the example code that generates the error:

```
  import pandas as pd
  import websockets                                  
                     
  async def test_func():  
      async with websockets.connect('ws://test.com') as ws:  
          await ws.send('hello')
          pd.DataFrame()
```

![image](https://user-images.githubusercontent.com/23005347/109261261-40f80680-7808-11eb-97ec-f06f0675aae8.png)

![image](https://user-images.githubusercontent.com/23005347/109261353-55d49a00-7808-11eb-8dd0-618a36fdadeb.png)

**Comment by glepnir** [comment] 2021-02-26 06:07
`:echo vim.o.columns`

**Comment by gshpychka** [comment] 2021-02-26 10:07
Can you reopen it? It's not solved for me.

The output of that command is 117.

**Comment by gshpychka** [comment] 2021-03-02 12:02
@glepnir any progress with this? Do you need additional info?

What about #126 ?

**Comment by glepnir** [comment] 2021-03-02 12:03
Sorry  a little busy on my work.  check this tomorrow.

**Comment by glepnir** [comment] 2021-03-03 08:22
Calculation formula for floating window,  If there is a file tree window on the left, subtract the width of the file tree window. then use this value x 0.7 . Use this value to prevent the content window from exceeding the border of the border window.
```
  local WIN_WIDTH = vim.o.columns

  if vim.fn.winnr('$') > 1 then
    local special_win = {
      ['NvimTree'] = true,
      ['NerdTree'] = true,
    }
    local first_win_id = api.nvim_list_wins()[1]
    local bufnr = vim.fn.winbufnr(first_win_id)
    local buf_ft = api.nvim_buf_get_option(bufnr,'filetype')
    if special_win[buf_ft] then
      WIN_WIDTH = WIN_WIDTH - vim.fn.winwidth(first_win_id)
    end
  end

  local _pad = width / WIN_WIDTH
  if _pad < 1 then
    width = math.floor(WIN_WIDTH *  0.7)
  else
    width = math.floor(WIN_WIDTH * 0.6)
  end
```
There are some problems in calculating the rows and columns of the content window using the border window. I haven't found a good way to solve it so far, so use a smaller width to avoid the content window beyond the border boundary. bfredl is making a built-in floating window api with a border. Maybe we will have a better way at that time

**Comment by gshpychka** [comment] 2021-03-03 08:40
Thanks. I'm not sure I understand, though, why the width changes. See my two screenshots - the width is different between the two, in the same file, same lspsaga version, neovim version, etc. I just move between these functions and the width changes.

**Comment by glepnir** [comment] 2021-03-03 08:43
yep because the doc has different length. use the max length of doc text as width .then use it / WIN_WIDTH.

**Comment by glepnir** [comment] 2021-03-03 08:46
notice the calculation formula  is  add into lspsaga just now. so I am not sure 0.7 or 0.6 can work with you. at least I create a 
columns = 117 window and your code to reproduce. like this
![image](https://user-images.githubusercontent.com/41671631/109778560-edd6e700-7c3f-11eb-8f1e-9b39ac21d910.png)
![image](https://user-images.githubusercontent.com/41671631/109778577-f3ccc800-7c3f-11eb-9aa2-4aae3d7a23e0.png)

**Comment by glepnir** [comment] 2021-03-03 08:47
If continue to increase the width. Then you will see the border beyond the border again. So compared with the default behavior, there will be calculation problems when using borders.

**Comment by gshpychka** [comment] 2021-03-03 10:02
Would it be possible to make the hoverdoc the same max width consistently, like with the built-in behavior?

**Comment by glepnir** [comment] 2021-03-03 11:33
hmm hover of default and lspsaga both use max length of doc text as window width. different is lspsaga will auto adjust according window and truncate.

**Comment by gshpychka** [comment] 2021-03-03 13:00
Okay, maybe you can add the option to keep the default behavior?

**Comment by glepnir** [comment] 2021-03-03 13:02
lspsaga do rpc request and use border window to render. so it's not relate default lsp handler. just use `vim.lsp.buf.hover0` .

**Comment by gshpychka** [comment] 2021-03-03 13:05
Okay, I will do that. Thanks.

To make sure I understand - you're truncating the width of the hoverdoc to make it prettier, but the way you calculate the width leads to inconsistent sizes, and you are not sure how to improve this? And a fix upstream by bfredl could help in the future?

This is good enough for me, I will use the built-in hoverdoc instead. I am not sure if I should close this issue, since the bug is still present - that's up to you.

**Comment by glepnir** [comment] 2021-03-03 13:14
I think upstream floating windows with borders are more useful. So currently I have not thought of a better way to deal with the border and content cross-border behavior. so I will close this issue.

**Closed** 2021-03-03 13:14 UTC
Labels: bug
