### ISSUE TITLE
Buggy when running `:Lspsaga rename`

### ISSUE THREAD

**Issue by segeljakt** [glepnir/lspsaga.nvim#726] opened 2023-01-18 09:49 UTC
### Describe the bug

Since the last update, I sometimes get errors when running `:Lspsaga rename`:

```
78398 exit
Error executing vim.schedule lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:458: Expected value but found unexpected end of string at character 83
stack traceback:
        [C]: in function 'decode'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:458: in function 'decode'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:465: in function <...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:453>

```

```
12454 exit
Error executing vim.schedule lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:458: Expected object key string but found unexpected end of string at character 248
stack traceback:
        [C]: in function 'decode'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:458: in function 'decode'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:465: in function <...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:453>

```

Other times it opens a preview window:

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/15143039/213138033-9f1518b2-6ea7-4078-9032-807543de5ba5.png">

### Steps to reproduce

`:LspSaga rename`

### Expected behavior

It should work like it used to

### Neovim version (nvim -v)

v0.9.0-dev-652+g438b4361c-dirty

### lspsaga commit

949234a

### Terminal name/version

iterm2 3.5.0beta9

**Comment by glepnir** [comment] 2023-01-18 09:50
quickly fix is disable `rename.whole_project = false`

**Comment by glepnir** [comment] 2023-01-18 09:51
there is would be better have a reproduce repo.  because there has some json decode need check.

**Comment by glepnir** [comment] 2023-01-18 09:53
it search this word in whole project . maybe need ignore some package management file like cargo.lock etc

**Comment by segeljakt** [comment] 2023-01-18 09:59
Ok, I'll keep you updated if I find anything more

**Comment by unTanana** [comment] 2023-01-18 10:48
I have a similar issue. The renaming is fine, but I think the additional part, with searching for the word in the whole project and then asking me if I want to mark the changes, that's what is bugging out. I don't want that functionality, but I do want to rename the variable in the whole project.
Is there a way to do that?

**Comment by glepnir** [comment] 2023-01-18 11:59
any other good idea is welcome.

**Comment by unTanana** [comment] 2023-01-18 12:00
Hey, thanks for taking the time to answer on this issue.
I've created this repo (with a video inside to show my issue)
https://github.com/unTanana/neovim-rename-test

Copy paste from the Readme in that repo:

What is happening?

I'm renaming the function *double* to doubleMe which correctly renames it at the place of definition, and at the place of usage.
I'm seeing an additional screen after the renaming is done, prompting me to rename any additional occurancess of "double" after that.

What I find to be wrong?

I don't want to rename words across the whole project, I just want the variable rename (simple, as it was in the past)
I can't close the additional screens unless I do :q on them (selecting them 1 by one)


Now, I am no pro at using neovim, so I apologise if there's an easy fix for this issue that I haven't found myself.

**Comment by glepnir** [comment] 2023-01-18 12:03
I had said the quickly fix is set this option to false `rename.whole_project` to false or we can popup a input list to ask you do you want to rename whole project the you need answer y or n . this is another way . but need i fix this json decode problem first ..

**Comment by glepnir** [comment] 2023-01-18 12:05
another way. a command argument . `Lspsaga rename ++project` if use this command it will work like current. if without this arugment it just do lsp rename.

**Comment by unTanana** [comment] 2023-01-18 12:12
you are right, setting `rename.whole_project` to false does work. My bad, I should have restarted neovim after changing that.
Thank you

**Comment by glepnir** [comment] 2023-01-18 12:14
it's okay! any talk is welcome . you give me a repo that can produce this it' very useful.

**Comment by glepnir** [comment] 2023-01-18 12:21
sorry your repo not reproduce this problem. it's workflow error. popup a window then you need use `x` to mark which file need rename then press `enter` to confirm rename.

**Comment by glepnir** [comment] 2023-01-18 12:21
this issue is json decode issue.

**Comment by unTanana** [comment] 2023-01-18 12:34
Hey, I do have this issue though, If I leave `whole_project` = true, and don't select anything in the window

https://user-images.githubusercontent.com/22821635/213172639-065cc46c-0feb-4bea-816e-c75b128437f3.mov

**Comment by unTanana** [comment] 2023-01-18 12:41
oh, oke

**Comment by glepnir** [comment] 2023-01-19 17:36
@unTanana  you issue should be solved.

@segeljakt can you give some example repo can trigger this json decode issue ?

**Closed** 2023-01-22 04:20 UTC
Labels: bug

**Comment by zggff** [comment] 2023-01-31 10:31
This bug still occurs for me when using on single file.

**Comment by glepnir** [comment] 2023-01-31 10:44
should be fixed now
