### ISSUE TITLE
lsp_finder error

### ISSUE THREAD

**Issue by SrMrBurchick** [glepnir/lspsaga.nvim#1008] opened 2023-04-06 16:56 UTC
### Describe the bug

lsp_finder stops working after first execution. It fails with that error:
```
Error executing vim.schedule lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:400: Vim:E481: No range allowe
d
stack traceback:
        [C]: in function 'nvim_win_call'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:400: in function 'create_finder_win'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:383: in function 'render_finder'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:165: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
After first time when lsp_finder has executed successfully, in neovim appears new buffer with `[No name]` and content of the ls_finder result
```
● Definition  1
   states/initializing.rs 1
     pub fn setup_scene

● References  1
   src/main.rs 1
     ializing::setup_scene

```
Same behavior on windows 

### Steps to reproduce

Open file with lsp client, run Lspsaga lsp_finder

### Expected behavior

Fork ok for next lspsaga lsp_fider execution, no creation any empty buff

### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### lspsaga commit

1253698: remove unused require

### Terminal name/version

alacrity Version 0.11.0 (8dbaa0bb), windows power shell

**Comment by glepnir** [comment] 2023-04-07 06:56
run in normal mode?

**Comment by SrMrBurchick** [comment] 2023-04-07 10:48
@glepnir Yep

**Comment by glepnir** [comment] 2023-04-07 10:48
can't reproduce it works fine on my local.

**Comment by SrMrBurchick** [comment] 2023-04-07 10:54
Ok, so i need to create it? Or it exists in lspsaga repositiry?

**Comment by glepnir** [comment] 2023-04-07 10:55
something like this 

```lua
vim.opt.runtimepath:append("~/dev/nvim-lspconfig/")
vim.opt.runtimepath:append("~/dev/lspsaga.nvim/")
local lspconfig = require("lspconfig") lspconfig.tsserver.setup({})
require('lspsaga').setup({})
lspconfig.tsserver.setup({})
lspconfig.eslint.setup({})
```

**Comment by SrMrBurchick** [comment] 2023-04-07 11:04
Works fine! But creates an empty buff after using lsp_finder on setup function

**Comment by glepnir** [comment] 2023-04-07 11:08
idk what you mean `creates an empty buffer`?

**Comment by SrMrBurchick** [comment] 2023-04-07 11:15
E37: No write since last change
E162: No write since last change for buffer "[No Name]"
Press ENTER or type command to continue

**Comment by glepnir** [comment] 2023-04-07 11:18
I don't think it create by finder i can't reproduce .

**Comment by SrMrBurchick** [comment] 2023-04-07 12:02
It's on min config((

**Comment by glepnir** [comment] 2023-04-07 12:04
please use clean env without loading any plugin.  `nvim --clean -u path/to/min` . the buffer create by finder is `wipe` .window close it will wipeout.

**Closed by glepnir** 2023-04-07 12:04 UTC
Labels: bug

**Comment by ui-HookeyChiang** [comment] 2023-04-15 18:15
@glepnir, thanks for the great work!
I'm also faced with this bug by executing lsp_finder and nvim emits the following:
```
Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/finder.lua:406: Vim(quit):E37: No write since last change
stack traceback:
        [C]: in function 'nvim_win_call'
        ...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/finder.lua:406: in function 'create_finder_win'
        ...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/finder.lua:389: in function 'render_finder'
        ...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/finder.lua:165: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Tracing down to finder.lua:406: `if vim.o.lines - 6 - opt.height - winline <= 0 then...`
If the cursor is put at the **bottom** of window, the bug can be reproduced easily.
Otherwise, put the cursor at the **top** of window, and it works like a charm.
