### ISSUE TITLE
Jumping to diagnostics with code actions breaks pressing the number keys

### ISSUE THREAD

**Issue by mgramigna** [glepnir/lspsaga.nvim#741] opened 2023-01-19 20:42 UTC
### Describe the bug

Weird issue, but when using `:Lspsaga diagnostic_jump_next` where the next diagnostic has code actions resolvable by pressing a number key, even after navigating away from the diagnostic, pressing that number key at all in the editor throws an error. Best shown through the following gif:

![demo](https://user-images.githubusercontent.com/16297930/213554445-be132916-6211-401b-9d57-155b0b8e4ea0.gif)

In the gif, the error is showing up when I press `1`, as that was the number corresponding to the code action.

### Steps to reproduce

1. Open a file with a diagnostic that has a code action. For my reproduction, I used a TypeScript file that calls a function that doesn't exist. The code action suggested is to add a definition for that function, e.g.

```ts
// I insert some blank lines so I can navigate away from the diagnostic

asdf(); // Has a code action to define the function in TypeScript
```

2. Jump to that diagnostic with `:Lspsaga diagnostic_jump_next`
3. Navigate away from the diagnostic so the window closes (I used `k` to just go up a line)
4. Press `1`, and the following error message appears

```
E5108: Error executing lua: .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction.lua:274: attempt to index field 'action_tuples' (a nil value)
stack traceback:
        .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction.lua:274: in function 'do_code_action'
        .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction.lua:206: in function <.../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction.lua:202>
```

### Expected behavior

Lspsaga should not be trying to execute the code action from a diagnostic that was closed (I assume that's what's happening) 

### Neovim version (nvim -v)

v0.9.0-dev-3418+gadfad50ac-dirty

### lspsaga commit

78d2898

### Terminal name/version

xterm-256color

**Comment by glepnir** [comment] 2023-01-20 03:25
can't reproduce.

![diagnostic](https://user-images.githubusercontent.com/41671631/213611282-fd4a493f-994a-4f14-bbe3-288ea08b36c5.gif)

**Comment by mgramigna** [comment] 2023-01-21 21:20
@glepnir I think the above .gif is not quite what I was doing to replicate the bug. The key is to move away from the diagnostic window before pressing the code action button.

Can you try again, but before pressing `1`, navigate away from the line where the diagnostic is? I am still getting the bug with a minimal config.

**Comment by iovis** [comment] 2023-01-21 22:08
I'm also having this issue

**Comment by glepnir** [comment] 2023-01-22 00:32
should be fixed.

**Closed by glepnir** 2023-01-22 00:32 UTC
Labels: bug

**Comment by mgramigna** [comment] 2023-01-22 01:53
@glepnir tysm

**Comment by iovis** [comment] 2023-01-22 06:50
Confirmed working using `require("lspsaga.diagnostic"):goto_prev()`

**Comment by glepnir** [comment] 2023-01-22 07:05
just use command it is same

**Comment by iovis** [comment] 2023-01-22 15:53
> just use command it is same

I was having an issue with the command version (looked like something about not finding the mappings anymore?), but it seems like you fixed it in a recent commit, thank you!
