### ISSUE TITLE
lsp_finder() not listing the references and definitions

### ISSUE THREAD

**Issue by muzaffar-omer** [glepnir/lspsaga.nvim#5] opened 2021-01-25 11:11 UTC
Hello,

Thanks a lot for this life-changing plugin for neovimers. It is amazing!

I observed the `lsp_finder()` function is not listing the definitions/references. I tried it in a Python repository.

`lua require'lspsaga.provider'.lsp_finder()`

Although `vim.lsp.buf.references()` is able to find the references.

I am using neovim version:

```
NVIM v0.5.0-dev+69103ff0c
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210125-92101-1jnyczu/build/config -I/tmp/neovim-20210125-92101-1jnyczu/src -I/usr/local/include -I/tmp/neovim-20210125-92101-1jnyczu/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210125-92101-1jnyczu/build/src/nvim/auto -I/tmp/neovim-20210125-92101-1jnyczu/build/include
Compiled by momer@LAP-CH-406-MAC.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-69103ff/share/nvim"

Run :checkhealth for more info
```

Also updated my `nvim-lspconfig` to the latest version using `PluginUpdate`.

Thanks for your help in advance

**Comment by onsails** [comment] 2021-01-25 11:22
Same happens for me in rust and python projects.

**Comment by glepnir** [comment] 2021-01-25 11:25
what happen for this 
```lua
:lua print(vim.inspect(vim.lsp.buf_request_sync(0, 'textDocument/references', params, timeout or 1000)))
```

**Comment by onsails** [comment] 2021-01-25 11:31
> what happen for this
> 
> ```lua
> :lua print(vim.inspect(vim.lsp.buf_request_sync(0, 'textDocument/references', params, timeout or 1000)))
> ```

prints `nil`

**Comment by muzaffar-omer** [comment] 2021-01-25 12:04
> ```lua
> lua print(vim.inspect(vim.lsp.buf_request_sync(0, 'textDocument/references', params, timeout or 1000)))
> ```

In my case prints `{}`

**Comment by muzaffar-omer** [comment] 2021-01-25 12:05
> what happen for this
> 
> ```lua
> :lua print(vim.inspect(vim.lsp.buf_request_sync(0, 'textDocument/references', params, timeout or 1000)))
> ```

In my case prints `{}`

**Comment by glepnir** [comment] 2021-01-25 13:42
which python serve do you used?

**Comment by muzaffar-omer** [comment] 2021-01-25 13:45
> which python serve do you used?

I am using `pyls` with the below configuration:

```
  require'lspconfig'.pyls.setup{
    cmd = { vim.g.python3_venv_bin .. "/pyls" },
    settings = {
      pyls = {
        configurationSources = { "pyflakes"},
        plugins = {
          jedi_completion = {
            fuzzy = false
          },
          pylint = {
            enabled = false,
            args = { "--jobs=4", "--rcfile=./.pylintrc"},
          },
          pydocstyle = {
            enabled = false,
            addIgnore = {"D100", "D101", "D103"},
          },
          pycodestyle = {
            enabled = false,
            maxLineLength = 100
          },
          pyflakes= {
            enabled = false,
          },
          flake8 = {
            enabled = true,
          }
        }
      }
    }
  }
```

**Comment by ckipp01** [comment] 2021-01-25 16:02
btw I just hit on this while using [`nvim-metals`](https://github.com/scalameta/nvim-metals) and Scala. I'm pretty sure the issue is that in the `textDocument/references` request that lspsaga sends, there is no `ReferenceContext` sent with the request, and it's not marked as optional. I'm pretty sure that's why in my case, the request is just returning null.

You can see the difference when you look at built-in nvim request vs the lspsaga request.

### Built in

```
[Trace - 04:56:00 PM] Received request 'textDocument/references - (7)'
Params: {
  "context": {
    "includeDeclaration": true
  },
  "textDocument": {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/tester/src/main/scala/example/Main.scala"
  },
  "position": {
    "line": 6,
    "character": 6
  }
}
```

### lspsaga
```
[Trace - 04:56:36 PM] Received request 'textDocument/references - (18)'
Params: {
  "textDocument": {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/tester/src/main/scala/example/Main.scala"
  },
  "position": {
    "line": 6,
    "character": 6
  }
}
```
Notice the missing `"context"`. You can read more about his here: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_references

**Comment by glepnir** [comment] 2021-01-26 01:41
#16  fix this.

**Closed by glepnir** 2021-01-26 01:41 UTC

**Comment by muzaffar-omer** [comment] 2021-01-26 01:55
> #16 fix this.

Thank you @glepnir @ckipp01 for the fix. I updated to the latest commit, now it works perfectly.

**Comment by glepnir** [comment] 2021-01-26 01:56
but auto preview window position looks wired. I am finding a good way to show it.

**Comment by muzaffar-omer** [comment] 2021-01-26 02:04
> but auto preview window position looks wired. I am finding a good way to show it.

Thanks for looking into it
